### ISSUE TITLE
Prices are totally unbalanced

### ISSUE THREAD

**Issue by Aberro** [KSP-RO/SovietRockets#1]
Prices for most parts and especially for engines makes them almost useless, because they are unbalanced with stock parts and most other mods. They should be at least ten times less than now and it would be better if they would be balanced to their Isp and thrust.
And, by the way, I'm not sure, but looks like weights are mismathed to too: one interstage decoupler (Proton 1/2 adapter) weight is ~4 tons while the other bigger one (Proton 2/3 adapter) is 2 tons; how could that be that smaller and simpler hollow part weighting two times more than bigger one with more metallic parts in it?

**Comment by raidernick** [comment]
I've stated dozens of times in the past I don't use, support or care about career mode. All prices are arbitrary values I made up. I've asked numerous times that if someone wants to balance the prices I would be happy to add them to the mod. So far in 3 years nobody has come forward to actually help, if you want it fixed feel free to do it.

Also the weights of the interstages have been subtracted from the main stage that they are attached to, so it is irrelevant how much they weigh. The reason they DO weigh that much is because not everyone has kerbal joint reinforcement and having a heavier part in KSP increases the node strength and makes it wobble less. So the weights are purposely like that to prevent wobbling. One part may be heavier than the other because it is prone to wobbling more. I can assure you though that extra weight has been accounted for in the mass of the rocket as a whole and is not affecting the payload weight.

**Comment by Aberro** [comment]
Well, OK, I'll try to find more or less balanced prices these weekend and I'll make a pull request, I hope (I'm currently using ~60 mods, but I'll try to match stock parts mostly, looking to modded parts as an example).

As about weights... well, I've didn't knew about that wobbling problem. It's still bad, because it's makes such parts useless for custom rockets, but I guess the problem isn't in this mod, but in KSP.

**Comment by raidernick** [comment]
Ok cool, when you do make the PR, do it to the experimental branch, not master. That branch will be replacing master on the next RO update.

**Comment by Aberro** [comment]
Done for Proton, I hope. Can or should I delete master branch (from my fork, of cource), in which I accidentally pushed commit at first try?

**Comment by raidernick** [comment]
I'm the wrong person to ask about that sorry, I know almost nothing about git, the bare minimum and whenever something breaks I need help from one of the RO guys to fix it.

**Comment by NathanKell** [comment]
@Aberro doesn't really matter. I'd suggest maybe resetting it to the last commit you want to keep, but that's only if you plan to use it again later. For now you needn't worry about it.

**Comment by raidernick** [comment]
merged
